wsdevelopment/config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  get 'collections/new'
  get 'collections/edit'
  get 'collections/show'
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      post 'unshare_with_friend' => 'notes#unshare_with_friend'
    end

    resources :friendships, only: [:index, :create, :update, :destroy]
    resources :collections, only: [:index, :create, :update, :destroy]
    resources :note_collections, only: [:index, :create, :update, :destroy, :edit]
    post 'add_note_to' => 'note_collections#add_note_to'
    post 'destroy_note_to' => 'note_collections#destroy_note_to'
    

  end

  root 'welcome#index'
end

wsdevelopment/app/models/user.rb
class User < ApplicationRecord

  has_many :notes, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :collections, dependent: :destroy
  has_and_belongs_to_many :note_permission
  has_and_belongs_to_many :note_collections

  before_save { self.email = email.downcase }
  validates :user_name, presence: true, length: { maximum: 10 },
    uniqueness: { case_sensitive: false }
  REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
  validates :email, presence: true, format: { with: REGEX_EMAIL },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }

end

wsdevelopment/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if logged?
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to users_path
      else
        render 'edit'
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, flash: {success: "Successfully Sign up"}
    else
      render 'new'
    end
  end

  def destroy
    if logged?
      @user = User.find(params[:id])
      @user.destroy

      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :admin)
  end

  def logged?
    session[:user_name]
  end
end

wsdevelopment/app/helpers/users_helper.rb
module UsersHelper
  def user_session_is_admin?
    if logged?
      admin = User.where(user_name: session[:user_name]).first.admin
    end
    admin
  end

  def get_user_name(user_id)
  	user = User.where(id: user_id).first
  end

  def get_user_id(user_name)
    user = User.find_by(user_name: user_name).id
  end
  def logged?
    session[:user_name]
  end
end

wsdevelopment/app/views/users/edit.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
<div class="col-md-9 col-lg-9 right_col">

  <!-- Row with title -->
  <div class="row page-title">
    <div class="title_left">
      <div class="x_panel panel-style">
        <h2 style="margin: 9px 0">Edit your user</h2> 
      </div>                
    </div>
  </div>
  <!-- /Row with title -->
  <div class="row center">
    <%= form_with scope: :user,  model:  @user ,class: 'col-xs-6', url: user_path, local: true do |form| %>
    <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= form.label :user_name %><br>
      <%= form.text_field :user_name, class: 'col-xs-12' %>
    </p>

    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email, class: 'col-xs-12' %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password, class: 'col-xs-12' %>
    </p>

    <p>
      <%= form.label :confirm_password %><br>
      <%= form.password_field :password_confirmation, class: 'col-xs-12' %>
    </p>

    <% if user_session_is_admin? %>
    <p>
      <%= form.label :admin, 'Admin' %><br>
      <%= form.radio_button :admin, :checked => false, :value => true %>
    </p>
    <% end %>

    <p>
      <%= form.submit %>
    </p>

    <% end %>

  </div>
  <div class="row center">
    <%= link_to 'Back', users_path, class: 'btn btn-info' %>
  </div>

  <% end %>

wsdevelopment/app/views/users/index.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <div  class="col-md-9 col-lg-9 right_col">
    <!-- Keep all page content within the page-content inset div! -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style" >
            <h2 style="margin: 9px 0"><i class="fa fa-cogs"></i> Admin Management</h2> 
          </div>
        </div>
      </div>
      <div class="row">
        <% @user.each do |user| %>
        <div class="note col-xs-12 col-sm-6 col-md-3 card-style">
          <div class="note-title col-xs-12">
            <%= user.user_name %>
          </div>
          <div class="note-text col-xs-12">
            <%= user.email %>
          </div>
          <div class="note-actions col-xs-12">
            <div class="col-xs-4 center">
              <%= link_to '<i class=" fa fa-sticky-note"></i>'.html_safe, user_notes_url(user), class: 'btn btn-default' %>
            </div>
            <div class="col-xs-4 center">
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user), class: 'btn btn-default' %>
            </div>
            <div class="col-xs-4 center">
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user_path(user), class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

wsdevelopment/app/views/users/new.html.erb
<body>
  <header class="container-fluid">
    <div class="center">
      <h1>New user</h1>
    </div>
  </header>

  <div id="main-content" class="container">
    <div class="row center">
      <%= form_with scope: :user, class: 'col-xs-6', url: users_path, local: true do |form| %>
        <% if @user.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2>
              <%= pluralize(@user.errors.count, "error") %> prohibited
              this note from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <p>
          <%= form.label :user_name %><br>
          <%= form.text_field :user_name, class: 'col-xs-12' %>
        </p>

        <p>
          <%= form.label :email %><br>
          <%= form.text_field :email, class: 'col-xs-12' %>
        </p>

        <p>
          <%= form.label :password %><br>
          <%= form.password_field :password, class: 'col-xs-12' %>
        </p>

        <p>
          <%= form.label :confirm_password %><br>
          <%= form.password_field :password_confirmation, class: 'col-xs-12' %>
        </p>
        <p>
          <%= form.submit %>
        </p>

      <% end %>

    </div>
    <div class="row center">
      <%= link_to 'Back', root_path, class: 'btn btn-info' %>
    </div>
  </div>
</body>

wsdevelopment/app/views/users/show.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <body>
    <div id="main-content" class="container">
      <div class="row center">
        <%= form_with scope: :user, class: 'col-xs-6', model: @users, local: true do |form| %>
          <p>
            <%= form.label :user_name %><br>
            <%= form.text_field :user_name, class: 'col-xs-12', :disabled => true %>
          </p>

          <p>
            <%= form.label :email %><br>
            <%= form.text_area :email, class: 'col-xs-12', :disabled => true, style: 'height: 200px'%>
          </p>

        <% end %>

      </div>
      <div class="row center col-xs-12">
        <%= link_to 'Back', users_path, class: 'btn btn-info with-margin' %>
      </div>
    </div>
  </body>
<% end %>