wsdevelopment/config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  get 'collections/new'
  get 'collections/edit'
  get 'collections/show'
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      post 'unshare_with_friend' => 'notes#unshare_with_friend'
    end

    resources :friendships, only: [:index, :create, :update, :destroy]
    resources :collections, only: [:index, :create, :update, :destroy]
    resources :note_collections, only: [:index, :create, :update, :destroy, :edit]
    post 'add_note_to' => 'note_collections#add_note_to'
    post 'destroy_note_to' => 'note_collections#destroy_note_to'
    

  end

  root 'welcome#index'
end

wsdevelopment/app/helpers/layouts_helper.rb
module LayoutsHelper
	def user_id(user_name)
		User.where(user_name: user_name).first.id
	end

	def user_name(user_id)
		User.where(id: user_id).first
	end
end

wsdevelopment/app/views/layouts/_nav.html.erb
<div class="nav_menu ">
 <div class="col-md-2 col-sm-2 col-xs-2 " style="float: left; padding-left: 15px; padding-top: 10px; font-size: 20px; ">
  <a id="menu_toggle" ><i class="glyphicon glyphicon-align-justify" style="cursor: pointer; color: #5a738e;"></i></a>
</div>
<div class="col-md-8 col-sm-8 col-xs-8 center">
 <!-- <h1>Title View</h1> -->
</div>
<div class="col-md-2 col-sm-2 col-xs-2 " align="center"style="padding-top: 10px; padding-bottom: 10px">
 <div class="dropdown">
  <%= image_tag("usuario.png", :alt => "image") %>
   <i class="dropdown-toggle" data-toggle="dropdown" style="font-size: 18px; cursor: pointer; color: #5a738e;" >
     <%= session[:user_name] %>
     <span class="caret"></span></i>
     <ul class="dropdown-menu">

       <li><%= link_to 'Log Out', '/logout' %></li>
     </ul>
   </div>

 </div>
</div>

wsdevelopment/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ClipUploader</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Upload New Image', new_photo_path %></li>
        </ul>
    </div>
  </div>
</nav>

wsdevelopment/app/views/layouts/_sidebar.html.erb
<%= javascript_include_tag "menu" %>
<%= stylesheet_link_tag "custom" %>

<% userId = user_id(session[:user_name])%>
<div class="left_col scroll-view" style="width: 100%">
	
  <!-- menu profile quick info -->
  <div class="profile clearfix" style="padding-top: 10px">
    <div class="profile_info">
      <p>Welcome, <%= session[:user_name] %></p>
    </div>
    <hr>
  </div>

  <!-- /menu profile quick info -->
  <!-- sidebar menu -->
  <div id="sidebar-menu" class="active main_menu_side hidden-print main_menu ">
    <div class="menu_section">
      <ul class="nav side-menu" id="nav-menu">
      	<% if user_session_is_admin? %>
	        <!-- User admin view -->
	        <li ><%= link_to '<i class="fa fa-sticky-note"></i> Notes list'.html_safe, user_notes_url(userId) %></li>
          <li ><%= link_to '<i class="fa fa-id-card-o"></i> Admin management'.html_safe, users_path %></li>
	        <!-- /User admin view -->
	    <% else %>
	    	<li ><%= link_to '<i class="fa fa-sticky-note"></i> Notes list'.html_safe, user_notes_url(userId) %></li>
	    <% end %>
        <!-- Collections view -->
        <li><%= link_to '<i class="fa fa-book"></i> Collections list'.html_safe, user_note_collections_url(userId) %>
        </li>
        <!-- /Collections view -->
        <!-- Friends view -->
        <li><%= link_to '<i class="fa fa-address-book"></i> Friends list'.html_safe, user_friendships_path(userId) %>
        </li>
        <!-- /Friends view -->  
        <!-- Edit view -->
        <li><%= link_to '<i class="fa fa-pencil"></i> Edit profile'.html_safe, edit_user_path(userId)  %>
        </li>
        <!-- /Edit view -->  
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->
</div>

wsdevelopment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wsdevelopment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Javascript-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" %>
    <!-- Stylesheet-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" %>
    
  </head>

  <body class="body nav-md ">
    <% if !logged? %>
      <%= yield %>
    <% else %>
      <header>
        <div class="top_nav">
          <%= render 'layouts/nav' %>  
        </div>
      </header>
      <main id="main" role="main">
        <div class="col-md-3 left_col">
          <%= render 'layouts/sidebar' %>
        </div>

        <%= yield %>
      </main>
    <% end %>
  </body>
</html>