wsdevelopment/config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  get 'collections/new'
  get 'collections/edit'
  get 'collections/show'
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      post 'unshare_with_friend' => 'notes#unshare_with_friend'
    end

    resources :friendships, only: [:index, :create, :update, :destroy]
    resources :collections, only: [:index, :create, :update, :destroy]
    resources :note_collections, only: [:index, :create, :update, :destroy, :edit]
    post 'add_note_to' => 'note_collections#add_note_to'
    post 'destroy_note_to' => 'note_collections#destroy_note_to'
    

  end

  root 'welcome#index'
end

wsdevelopment/app/models/note_collection.rb
class NoteCollection < ApplicationRecord

  has_and_belongs_to_many :user
  has_and_belongs_to_many :note

end

wsdevelopment/app/controllers/note_collections_controller.rb
class NoteCollectionsController < ApplicationController

  def index
    @collection = NoteCollection.all
  end

  def edit
    @note_collection = NoteCollection.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    nc = NoteCollection.create({title: params[:title], creator_id: params[:user_id]})
    nc.user << @user
    redirect_to user_note_collections_url
  end

  def update
    @note_collection = NoteCollection.find(params[:id])
    @note_collection.update_column(:title, params[:note_collection][:title])
    redirect_to user_note_collections_url
  end

  def destroy
    if session[:user_name]
      @collection = NoteCollection.find(params[:id])

      if @collection.destroy
        redirect_to user_note_collections_url
      end
    end
  end

  def add_note_to
    if session[:user_name]
      note = Note.find(params[:note_id])
      @note_collection = NoteCollection.find(params[:id]).note << note
      redirect_to user_note_collections_url
    end
  end

  def destroy_note_to
    if session[:user_name]
      note = Note.find(params[:note_id])
      @note_collection = NoteCollection.find(params[:id])
      @note_collection.note.delete(Note.find(params[:note_id]))
      redirect_to user_note_collections_url
    end
  end
end

wsdevelopment/app/helpers/note_collection_helper.rb
module NoteCollectionHelper
end

wsdevelopment/app/helpers/note_collections_helper.rb
module NoteCollectionsHelper
  def find_collections(user_id)
    NoteCollection.select{|nc| nc.user_ids.include?(user_id)}
  end

  def find_notes_in_collection(collection_id)
  	NoteCollection.find(collection_id).note
  end
end

wsdevelopment/app/views/note_collections/edit.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
<div class="col-md-9 col-lg-9 right_col">
   <!-- Row with title -->
   <div class="row page-title">
     <div class="title_left">
       <div class="x_panel panel-style">
         <h2 style="margin: 9px 0"><%= @note_collection.title %> / Edit </h2> 
       </div>
     </div>
   </div>
   <!-- /Row with title -->

   <div class="row center">
     <%= form_with(scope: :note_collection, model: [ :user, @note_collection ], class: 'col-xs-6', local: true) do |form| %>
       <% if @note_collection.errors.any? %>
         <div id="error_explanation" class="alert alert-danger">
           <h2>
             <%= pluralize(@note.errors.count, "error") %> prohibited
             this note from being saved:
           </h2>
           <ul>
             <% @note.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>

       <p>
         <%= form.label :title %><br>
         <%= form.text_field :title, class: 'col-xs-9' %>
         <%= form.submit %>
       </p>


 <% end %>
   </div>

   <!-- Allow to edit users -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <h4 style="margin: 9px 0">Added Notes </h4>
          </div>
        </div>
      </div>
        <div class="row">
        <% user_id = get_user_id(session[:user_name]) %>
        <% find_notes_in_collection(@note_collection.id).each do |note|  %>
          
          <div class="note col-xs-12 col-sm-6 col-md-3" style="height: 200px">
              <div class="row">
                <% if note.image.url %>
                  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <div >
                      <span>
                        <%= image_tag(note.image.url, alt: 'Image', class: 'note-image') if note.image? %>
                      </span>
                    </div>
                  </div>
                <% end %>  
                <div class="note-title col-xs-12 col-sm-4 col-md-4 col-lg-4" style="padding-left: 30px">
                  <%= note.title %>
                </div>
              </div>
              <div class="row" style="height: 40%">
                <div class="note-text col-xs-12 col-lg-12 col-md-12">
                  <%= note.text %>
                </div>
              </div>
              <div class="row" style="padding-left:25px; padding-right: 25px ">
                <div class="col-xs-12" align="right">
                  <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user_destroy_note_to_path({id: @note_collection.id, user_id: user_id, note_id: note.id}), :method => :post, class: 'btn btn-danger'%>
                </div>           
                
              </div>
            </div>
        <% end %>
      </div>
    </div>


    <!-- Add new user to share -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <h4 style="margin: 9px 0">All notes </h4>
          </div>
        </div>
      </div>
      <div class="row">
        <% user_id = get_user_id(session[:user_name]) %>
        <% get_notes(user_id).each do |note|  %>
        <% if !@note_collection.note.include?(Note.find(note.id))%>
          <div class="note col-xs-12 col-sm-6 col-md-3" style="height: 200px">
              <div class="row">
                <% if note.image.url %>
                  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <div >
                      <span>
                        <%= image_tag(note.image.url, alt: 'Image', class: 'note-image') if note.image? %>
                      </span>
                    </div>
                  </div>
                <% end %>  
                <div class="note-title col-xs-12 col-sm-4 col-md-4 col-lg-4" style="padding-left: 30px">
                  <%= note.title %>
                </div>
              </div>
              <div class="row" style="height: 40%">
                <div class="note-text col-xs-12 col-lg-12 col-md-12">
                  <%= note.text %>
                </div>
              </div>
              <div class="row" style="padding-left:25px; padding-right: 25px ">
                <div class="col-xs-12" align="right">
                  <%= link_to '<i class="fa fa-plus"></i>'.html_safe, user_add_note_to_path({id: @note_collection.id, user_id: user_id, note_id: note.id}), :method => :post, class: 'btn btn-default'%>
                </div>           
                
              </div>
            </div>
          <% end %>   
        <% end %>
      </div>
    </div>
 <% end %>

wsdevelopment/app/views/note_collections/index.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <div class="col-md-9 col-lg-9 right_col" >
    <div class="row page-title">
      <div class="title_left">
        <div class="x_panel panel-style">
            <h3 style="margin: 9px 0">Notes Collections</h3>
        </div>
      </div>
    </div>
    <% user_id = get_user_id(session[:user_name])%>
    
    <div class="row">
      <% collections = find_collections(user_id) %>
      <% collections.each do |collection| %>
      <div class="note col-xs-12 col-sm-6 col-md-3">
        <div class="note-title col-xs-12">
          <%= collection.title %>
        </div>
        <div class="note-actions col-xs-12">
          <div class="col-xs-4 center">
            <%= link_to '<i class=" fa fa-sticky-note"></i>'.html_safe, { controller: 'note_collections', action: 'edit', id: collection.id }, class: 'btn btn-default' %>
          </div>
          <div class="col-xs-4 center">
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, { controller: 'note_collections', action: 'destroy', id: collection.id }, class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="note col-xs-12 col-sm-6 col-md-3" style="height: 150px; ">
              <div class="row" style="font-size: 30px; display: flex; justify-content: center; padding-top:60px">                  
                  <%= link_to '<i class="fa fa-plus"></i>'.html_safe, user_note_collections_path(:user_id => user_id, :title => "<new collection>"), :method => :create  %>
              </div>
            </div>
    </div>



  <% end %>

wsdevelopment/app/views/note_collections/new.html.erb
<h1>Collections#new</h1>
<p>Find me in app/views/collections/new.html.erb</p>

wsdevelopment/app/views/note_collections/show.html.erb
<h1>Collections#show</h1>
<p>Find me in app/views/collections/show.html.erb</p>