wsdevelopment/config/routes.rb
Rails.application.routes.draw do
  get 'collections/index'
  get 'collections/new'
  get 'collections/edit'
  get 'collections/show'
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      post 'unshare_with_friend' => 'notes#unshare_with_friend'
    end

    resources :friendships, only: [:index, :create, :update, :destroy]
    resources :collections, only: [:index, :create, :update, :destroy]
    resources :note_collections, only: [:index, :create, :update, :destroy, :edit]
    post 'add_note_to' => 'note_collections#add_note_to'
    post 'destroy_note_to' => 'note_collections#destroy_note_to'
    

  end

  root 'welcome#index'
end

wsdevelopment/app/models/note.rb
class Note < ApplicationRecord

  belongs_to :user
  has_one :note_permission, dependent: :destroy
  has_many :collections_notes, through: :collections_notes
  has_and_belongs_to_many :note_collection

  validates :title, presence: true, length: {maximum: 10}
  validates :text, presence: true

mount_uploader :image, ImageUploader
end

wsdevelopment/app/models/note_collection.rb
class NoteCollection < ApplicationRecord

  has_and_belongs_to_many :user
  has_and_belongs_to_many :note

end

wsdevelopment/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @note = Note.all
  end
  def show
    @note = Note.find(params[:id])
  end

  def new
    @note=Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    if logged?
      user = User.where(user_name: session[:user_name]).first
      @note = Note.find(params[:id])
      
      if @note.update(note_params)
        redirect_to user_notes_url(user.id)
      else
        render 'edit'
      end
    end
  end

  def create
    if logged?
      @user = User.find(params[:user_id])
      @note = @user.notes.create(note_params)

      if @note.save
        np = NotePermission.create({note: @note})
        np.user << @user
        redirect_to user_notes_url(@user)
      else
        render 'new'
      end
    end
  end

  def share
    @note = Note.find(params["note_id"])
    @note_permission = @note.note_permission
  end

  def share_with_friend
    note = Note.find(params["note_id"])
    note_permission = note.note_permission
    note_permission.user << User.find(params[:friend_id])
    redirect_to user_note_share_url(note)
  end

  def unshare_with_friend
    note = Note.find(params["note_id"])
    note_permission = note.note_permission
    note_permission.user.delete(User.find(params[:friend_id]))
    redirect_to user_note_share_url(note)
  end

  def destroy
    if logged?
      @note = Note.find(params[:id])
      @user = User.find(@note.user_id)
      @note.destroy

      redirect_to user_notes_url(@user)
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :text, :image)
  end

  def logged?
    session[:user_name]
  end
end

wsdevelopment/app/helpers/notes_helper.rb
module NotesHelper

  def find_notes(user_id)
    notes = []
    friendships = get_friendships(user_id, 'confirmed')

    notes = Note.where(user_id: user_id.to_i)

    friendships.each do |friendship|
      friendship.user_id == user_id.to_i ? id = friendship.friend_id  : id = friendship.user_id
      notes = notes +  Note.where(user_id: id)
    end

    notes = notes.group_by(&:user_id)        
  end

  def user_session_is_admin?
    if logged?
      admin = User.where(user_name: session[:user_name]).first.admin
    end
    admin
  end

  def get_users_to_edit(note_id)
    note = Note.find(note_id)
    note.note_permission.user - Array.wrap(note.user)
  end

  def get_users_cant_edit(note_id)
    note = Note.find(note_id)
    User.where.not(id: note.note_permission.user_ids)
  end

  def get_notes(user_id)
    note = Note.where(user_id: user_id)
  end

  def logged?
    session[:user_name]
  end
end

wsdevelopment/app/views/notes/edit.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
<div class="col-md-9 col-lg-9 right_col">
   <!-- Row with title -->
   <div class="row page-title">
    <div class="title_left">
      <div class="x_panel">
        <h2 style="margin: 9px 0"> 
          <%= @note.title %>/ Edit </h2> 
      </div>                
    </div>
  </div>
  <!-- /Row with title -->
  <div class="row center">
    <%= form_with(scope: :note, model: [ :user, @note ], class: 'col-xs-6', local: true) do |form| %>
    <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'col-xs-12' %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text, class: 'col-xs-12', style: 'height: 200px' %>
    </p>

    <p>
      <%= form.label :image %><br>
      <%= image_tag(@note.image.url, alt: 'Image', class: 'col-xs-12 center', style: 'padding-bottom: 1rem;') if @note.image? %>
      <%= form.file_field :image, class: 'col-xs-12'%>
    </p>

    <p>
      <%= form.submit %>
    </p>

    <% end %>

  </div>
  <div class="row center">
    <%= link_to 'Back', user_notes_url(params[:user_id]), class: 'btn btn-info' %>
  </div>
</div>
<% end %>

wsdevelopment/app/views/notes/index.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <div class="col-md-9 col-lg-9 right_col">
    <% notes = find_notes(params[:user_id]) %>    
    <% notes.each_pair do |user_id, user_notes| %>
      <!-- Row with title -->
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <% if user_id == params[:user_id].to_i %>
              <% user = get_user_name(user_id) %>  
              <h3 style="margin: 9px 0"><i class="fa fa-sticky-note"></i> 
                <%= user.user_name %> Notes
              </h3> 
            <% else %>
              <% user = get_user_name(user_id) %>
              <h3 style="margin: 9px 0"><i class="fa fa-sticky-note"></i>
                <%= user.user_name %> Notes
              </h3> 
            <% end %>
          </div>
        </div>
      </div>
      <!-- / Row with title --> 
        <div class="row" style="padding-left: 60px">
          <% user_notes.each do |note| %>
            <div class="note col-xs-12 col-sm-6 col-md-3" style="height: 200px">
              <div class="row">
                <% if note.image.url %>
                  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <div >
                      <span>
                        <%= image_tag(note.image.url, alt: 'Image', class: 'note-image') if note.image? %>
                      </span>
                    </div>
                  </div>
                <% end %>  
                <div class="note-title col-xs-12 col-sm-4 col-md-4 col-lg-4" style="padding-left: 30px">
                  <%= note.title %>
                </div>
              </div>
              <div class="row" style="height: 40%">
                <div class="note-text col-xs-12 col-lg-12 col-md-12">
                  <%= note.text %>
                </div>
              </div>
              <div class="row" style="padding-left:25px; padding-right: 25px ">
                <div class="col-xs-3 center">
                  <%= link_to '<i class="fa fa-eye"></i>'.html_safe, { controller: 'notes', action: 'show', id: note }, class: 'btn btn-default' %>
                </div>
                <% if note.note_permission&.user_ids&.include?(get_user_id(session[:user_name])) %>
                    <div class="col-xs-3 center">
                      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, { controller: 'notes', action: 'edit', id: note }, class: 'btn btn-default' %>
                    </div>
                    <div class="col-xs-3 center">
                      <%= link_to '<i class="fa fa-share"></i>'.html_safe, user_note_share_path({note_id: note.id}), class: 'btn btn-default', method: :get %>
                    </div>
                    <div class="col-xs-3 center">
                      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, { controller: 'notes', action: 'destroy', id: note }, class: 'btn btn-danger',
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
                    </div>
                <% end %>
              </div>
            </div>

          <% end %>
          <% if user_id == params[:user_id].to_i %>
            <div class="note col-xs-12 col-sm-6 col-md-3" style="height: 200px; ">
              <div class="row" style="font-size: 30px; display: flex; justify-content: center; padding-top:85px">                  
                  <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_user_note_url %>  
              </div>
            </div>
          <% end %>
        </div>      
    <% end %>
    <% if user_session_is_admin? %>
      <div class="row center">
        <%= link_to 'Back', users_url, class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
<% end %>

wsdevelopment/app/views/notes/new.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
<div class="col-md-9 col-lg-9 right_col">
  <!-- Row with title -->
  <div class="row page-title">
    <div class="title_left">
      <div class="x_panel">
        <h2 style="margin: 9px 0">Create note</h2> 
      </div>                
    </div>
  </div>
  <!-- /Row with title -->
  <% if @note.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
      <%= pluralize(@note.errors.count, "error") %> prohibited
      this note from being saved:
    </h2>
    <ul>
      <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row center">
    <%= form_with scope: :note, model: [ :user, @note ], class: 'col-xs-6', local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'col-xs-12' %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text, class: 'col-xs-12', style: 'height: 200px'%>
    </p>

    <p>
      <%= form.label :image %><br>
      <%= form.file_field :image, class: 'col-xs-12'%>
    </p>

    <p>
      <%= form.submit %>
    </p>

    <% end %>

  </div>
  <div class="row center">
    <%= link_to 'Back', user_notes_url(params[:user_id]), class: 'btn btn-info' %>
  </div>
</div>
<% end %>

wsdevelopment/app/views/notes/share.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>

  <div  class="col-md-9 col-lg-9 right_col">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <% user_id = user_id(session[:user_name]) %>
    <!-- Keep all page content within the page-content inset div! -->

    <!-- creator user -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <h4 style="margin: 9px 0">Note creator</h4>
          </div>
        </div>
      </div>
      <div class="row">
        <% user = @note.user %>
        <!-- User info-->
        <div class="note col-xs-12 col-sm-6 col-md-3">
          <!-- User icon-->
          <div class="col-lg-2 col-md-2 col-xs-12">
            <div class="row" align="center">
              <i class="fa fa-user user-icon" ></i>
            </div>
          </div>
          <!-- /User icon-->
          <!-- User name-->
          <div class="col-lg-8 col-md-8">
            <div class="note-title col-xs-12">
              <%= user.user_name%>
            </div>
            <div class="note-text col-xs-12">
              <%= user.email %>
            </div>
          </div>
          <!-- /User name-->
        </div>
        <!-- User info-->
      </div>
    </div>

    <!-- Allow to edit users -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <h4 style="margin: 9px 0">Allow to edit </h4>
          </div>
        </div>
      </div>
      <div class="row">
        <% get_users_to_edit(@note.id).each do |user|  %>
          <!-- User info-->
          <div class="note col-xs-12 col-sm-6 col-md-3">
            <!-- User icon-->
            <div class="col-lg-2 col-md-2 col-xs-12">
              <div class="row" align="center">
                <i class="fa fa-user user-icon" ></i>
              </div>
            </div>
            <!-- /User icon-->
            <!-- User name-->
            <div class="col-lg-8 col-md-8">
              <div class="note-title col-xs-12">
                <%= user.user_name%>
              </div>
              <div class="note-text col-xs-12">
                <%= user.email %>
              </div>
            </div>
            <!-- /User name-->
            <!-- Delete button -->
            <div class="col-md-2 col-lg-2">
              <div class="row center" style="padding-top: 2rem">
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user_note_unshare_with_friend_path({id: user_id, friend_id: user.id}), :method => :post, class: 'btn btn-danger'%>
              </div>
            </div>
            <!-- /Delete button -->
          </div>
          <!-- User info-->
        <% end %>
      </div>
    </div>


    <!-- Add new user to share -->
    <div class="page-content inset">
      <div class="row page-title">
        <div class="title_left">
          <div class="x_panel panel-style">
            <h4 style="margin: 9px 0">Not allow to edit </h4>
          </div>
        </div>
      </div>
      <div class="row">
        <% get_users_cant_edit(@note.id).each do |user|  %>
          <!-- User info-->
          <div class="note col-xs-12 col-sm-6 col-md-3">
            <!-- User icon-->
            <div class="col-lg-2 col-md-2 col-xs-12">
              <div class="row" align="center">
                <i class="fa fa-user user-icon" ></i>
              </div>
            </div>
            <!-- /User icon-->
            <!-- User name-->
            <div class="col-lg-8 col-md-8">
              <div class="note-title col-xs-12">
                <%= user.user_name%>
              </div>
              <div class="note-text col-xs-12">
                <%= user.email %>
              </div>
            </div>
            <!-- /User name-->
            <!-- Delete button -->
            <div class="col-md-2 col-lg-2">
              <div class="row center" style="padding-top: 2rem">
                <%= link_to '<i class="fa fa-plus"></i>'.html_safe, user_note_share_with_friend_path({id: user_id, friend_id: user.id}), :method => :post, class: 'btn btn-default'%>
              </div>
            </div>
            <!-- /Delete button -->
          </div>
          <!-- User info-->
        <% end %>
      </div>
    </div>


  </div>
<% end %>

wsdevelopment/app/views/notes/show.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
  <div class="col-md-9 col-lg-9 right_col">
        <div class="page-content inset">
         <!-- Row with title -->
         <div class="row page-title">
          <div class="title_left">
            <div class="x_panel">
              <h2 style="margin: 9px 0">Note_name </h2> 
            </div>                
          </div>
        </div>
        <!-- /Row with title -->
        <div class="row center">
          <%= form_with(model: [ :user, @note ], class: 'col-xs-6', local: true) do |form| %>
          <p>
            <%= form.label :title %><br>
            <%= form.text_field :title, class: 'col-xs-12', :disabled => true %>
          </p>

          <p>
            <%= form.label :text %><br>
            <%= form.text_area :text, class: 'col-xs-12', :disabled => true, style: 'height: 200px'%>
          </p>

          <p>
            <%= form.label :image %><br>
            <%= image_tag(@note.image.url, alt: 'Image', class: 'col-xs-12 center') if @note.image? %>
          </p>

          <% end %>

        </div>
        <div class="row center col-xs-12">
          <%= link_to 'Edit', edit_user_note_url, class: 'btn btn-default with-margin' %>
          <%= link_to 'Back', user_notes_url(params[:user_id]), class: 'btn btn-info' %>
        </div>
      </div>
</div>
<% end %>